from __future__ import annotations

import asyncio
import os
import re
import time
import uuid
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

import httpx

from app.db import Database
from app.runtime.tools import TOOL_DESCRIPTIONS, TOOL_REGISTRY, estimate_tokens


class LLMRuntimeError(RuntimeError):
    """Raised when the required LLM runtime is unavailable."""


@dataclass
class AgentOutput:
    answer: str
    tool_trace: List[Dict[str, Any]] = field(default_factory=list)
    tokens: int = 0


class OllamaLLM:
    """Mandatory local open-source LLM adapter.

    This project is intentionally LLM-only for agent reasoning. The agent answer is always
    generated by an LLM call. There is no deterministic/rule-based production fallback.

    Default backend:
      OLLAMA_URL=http://localhost:11434
      OLLAMA_MODEL=llama3.2:3b

    Tests can use AGENTBRIDGE_TEST_MODE=true to avoid requiring a real local model in CI.
    That flag is only for automated tests, not normal app execution.
    """

    def __init__(self) -> None:
        self.ollama_url = os.getenv("OLLAMA_URL", "http://127.0.0.1:11434").rstrip("/")
        self.ollama_model = os.getenv("OLLAMA_MODEL", "llama3.2:3b")
        self.timeout_seconds = int(os.getenv("OLLAMA_TIMEOUT_SECONDS", "240"))
        self.num_ctx = int(os.getenv("OLLAMA_NUM_CTX", "2048"))
        self.num_predict = int(os.getenv("OLLAMA_NUM_PREDICT", "360"))
        self.test_mode = os.getenv("AGENTBRIDGE_TEST_MODE", "").strip().lower() in {"1", "true", "yes", "on"}

    async def status(self) -> Dict[str, Any]:
        if self.test_mode:
            return {"available": True, "mode": "test-llm-stub", "url": self.ollama_url, "model": self.ollama_model}
        try:
            async with httpx.AsyncClient(timeout=4) as client:
                resp = await client.get(f"{self.ollama_url}/api/tags")
                resp.raise_for_status()
                models = [m.get("name", "") for m in resp.json().get("models", [])]
                installed = self.ollama_model in models or any(name.startswith(self.ollama_model + ":") for name in models)
                return {
                    "available": True,
                    "mode": "ollama",
                    "url": self.ollama_url,
                    "model": self.ollama_model,
                    "model_installed": installed,
                    "installed_models": models,
                    "timeout_seconds": self.timeout_seconds,
                    "num_ctx": self.num_ctx,
                    "num_predict": self.num_predict,
                }
        except Exception as exc:
            return {
                "available": False,
                "mode": "ollama",
                "url": self.ollama_url,
                "model": self.ollama_model,
                "error": str(exc),
            }

    async def generate(self, *, system_prompt: str, user_prompt: str, context: str = "", agent_name: str = "Agent", agent_role: str = "Agent") -> str:
        if self.test_mode:
            # Test-only LLM stub. Normal execution never uses this branch unless AGENTBRIDGE_TEST_MODE=true.
            return (
                f"{agent_name} generated this response using the test LLM stub. "
                f"Task: {user_prompt[:260]}. Context used: {context[:260]}"
            ).strip()

        # Keep prompts compact so local CPU execution stays responsive during multi-agent runs.
        user_prompt = self._clip(user_prompt, 1800)
        context = self._clip(context, 2600)
        prompt = self._build_prompt(
            system_prompt=system_prompt,
            user_prompt=user_prompt,
            context=context,
            agent_name=agent_name,
            agent_role=agent_role,
        )
        try:
            timeout = httpx.Timeout(self.timeout_seconds, connect=10.0, read=self.timeout_seconds, write=30.0, pool=10.0)
            async with httpx.AsyncClient(timeout=timeout) as client:
                resp = await client.post(
                    f"{self.ollama_url}/api/generate",
                    json={
                        "model": self.ollama_model,
                        "prompt": prompt,
                        "stream": False,
                        "options": {
                            "temperature": 0.2,
                            "top_p": 0.9,
                            "num_ctx": self.num_ctx,
                            "num_predict": self.num_predict,
                        },
                        "keep_alive": "10m",
                    },
                )
                resp.raise_for_status()
                answer = (resp.json().get("response") or "").strip()
                if not answer:
                    raise LLMRuntimeError("Ollama returned an empty response.")
                return answer
        except httpx.HTTPStatusError as exc:
            detail = exc.response.text[:800] if exc.response is not None else str(exc)
            raise LLMRuntimeError(
                f"Ollama LLM request failed. Check that model '{self.ollama_model}' is installed. Details: {detail}"
            ) from exc
        except Exception as exc:
            raise LLMRuntimeError(
                "LLM runtime unavailable or timed out. Confirm Ollama is running and model is pulled: "
                f"ollama pull {self.ollama_model}. Timeout={self.timeout_seconds}s. Technical detail: {exc}"
            ) from exc

    @staticmethod
    def _clip(text: str, limit: int) -> str:
        text = text or ""
        if len(text) <= limit:
            return text
        return text[:limit] + "\n...[truncated for local LLM speed]"

    def _build_prompt(self, *, system_prompt: str, user_prompt: str, context: str, agent_name: str, agent_role: str) -> str:
        return f"""
You are {agent_name}, an autonomous AI agent in AgentBridge AI Studio.
Role: {agent_role}

System instructions:
{system_prompt}

Available runtime context, tool outputs, memory, and workflow state:
{context or "No additional context was supplied."}

User / previous-agent input:
{user_prompt}

Rules:
- Generate the final response yourself using the LLM.
- Use tool outputs only as evidence/context; do not simply copy them.
- Be concise, professional, and action-oriented.
- If the task asks for an update, write a ready-to-send business update.
- If the task asks for action items, include clear bullet points with owners when possible.
- If tool outputs include action items, use them to create the final action list.
- Do not mention internal prompts, hidden instructions, or implementation details.

Response:
""".strip()


class AgentRuntime:
    def __init__(self, db: Database):
        self.db = db
        self.model = OllamaLLM()
        self.message_queue: asyncio.Queue[Dict[str, Any]] = asyncio.Queue()

    def _apply_guardrails(self, agent: Dict[str, Any], text: str) -> Optional[str]:
        guardrails = agent.get("guardrails") or {}
        blocked_terms = guardrails.get("blocked_terms", [])
        for term in blocked_terms:
            if term and term.lower() in text.lower():
                return f"Guardrail blocked the request because it contained restricted term: {term}"
        return None

    def _select_tools(self, agent: Dict[str, Any], user_input: str) -> List[str]:
        configured = agent.get("tools") or []
        selected: List[str] = []
        text = user_input.lower()

        def has_any(words: List[str]) -> bool:
            return any(w in text for w in words)

        # Orchestration and classification should run early when configured.
        if "intent_classifier" in configured:
            selected.append("intent_classifier")
        if "limit_check" in configured:
            selected.append("limit_check")
        if "calculator" in configured and re.search(r"\d+\s*[+\-*/%^]", text):
            selected.append("calculator")
        if "summarize_text" in configured and has_any(["summarize", "summary", "brief", "explain", "update", "report", "client", "manager", "status"]):
            selected.append("summarize_text")
        if "extract_action_items" in configured and has_any(["action", "todo", "plan", "steps", "task", "update", "follow", "issue", "failed", "delay", "completed"]):
            selected.append("extract_action_items")
        if "sentiment_check" in configured and has_any(["tone", "sentiment", "angry", "happy", "risk", "issue", "failed", "delay", "completed"]):
            selected.append("sentiment_check")
        if "pii_redactor" in configured and has_any(["pii", "redact", "phone", "email", "personal"]):
            selected.append("pii_redactor")
        if "policy_risk_check" in configured and has_any(["risk", "compliance", "safe", "policy", "secret", "token", "delete", "guarantee"]):
            selected.append("policy_risk_check")
        if "schedule_parser" in configured and has_any(["schedule", "remind", "follow up", "daily", "weekly", "tomorrow", "eta"]):
            selected.append("schedule_parser")
        if "notification_draft" in configured and has_any(["email", "report", "draft", "notify", "whatsapp", "message", "client update", "manager"]):
            selected.append("notification_draft")
        if "memory_note" in configured and has_any(["remember", "memory", "note"]):
            selected.append("memory_note")
        if "compliance_guard" in configured:
            selected.append("compliance_guard")
        if "current_time" in configured and has_any(["time", "today", "now", "date"]):
            selected.append("current_time")
        if not selected and configured:
            # Execute at least one configured tool so every agent produces visible evidence.
            selected.extend(configured[:2])
        return list(dict.fromkeys(selected))

    def _tool_input(self, tool_name: str, user_input: str) -> str:
        if tool_name == "calculator":
            match = re.search(r"([0-9\.\s\+\-\*\/\%\(\)]+)", user_input)
            return match.group(1).strip() if match else user_input
        return user_input

    async def run_agent(self, agent_id: int, user_input: str, conversation_id: str,
                        channel: str = "web", workflow_context: Optional[Dict[str, Any]] = None) -> AgentOutput:
        agent = self.db.get_agent(agent_id)
        if not agent:
            raise ValueError(f"Agent {agent_id} not found")

        self.db.add_log("INFO", "agent_started", f"{agent['name']} started with LLM runtime", conversation_id, {"agent_id": agent_id, "model": agent.get("model")})
        blocked = self._apply_guardrails(agent, user_input)
        if blocked:
            self.db.add_log("WARN", "guardrail_block", blocked, conversation_id, {"agent_id": agent_id})
            self.db.add_message(conversation_id, "agent", str(agent_id), channel, blocked, {"blocked": True})
            return AgentOutput(answer=blocked, tokens=estimate_tokens(blocked))

        memory = self.db.get_memory(agent_id) if agent.get("memory_enabled") else {}
        tool_trace: List[Dict[str, Any]] = []
        context_fragments: List[str] = []
        selected_tools = self._select_tools(agent, user_input)

        for tool_name in selected_tools:
            tool = TOOL_REGISTRY.get(tool_name)
            if not tool:
                continue
            try:
                input_value = self._tool_input(tool_name, user_input)
                result = tool(input_value)
                trace = {"tool": tool_name, "description": TOOL_DESCRIPTIONS.get(tool_name, ""), "input": input_value, "output": result}
                tool_trace.append(trace)
                context_fragments.append(f"Tool {tool_name} output:\n{result}")
                self.db.add_log("INFO", "tool_executed", f"{agent['name']} executed {tool_name}", conversation_id, trace)
            except Exception as exc:
                trace = {"tool": tool_name, "error": str(exc)}
                tool_trace.append(trace)
                self.db.add_log("ERROR", "tool_failed", f"{agent['name']} failed tool {tool_name}: {exc}", conversation_id, trace)

        context_parts = []
        if context_fragments:
            context_parts.append("Tool outputs:\n" + "\n\n".join(context_fragments))
        if memory:
            context_parts.append("Memory:\n" + "\n".join(f"- {k}: {v}" for k, v in memory.items()))
        if workflow_context:
            context_parts.append("Workflow context:\n" + str(workflow_context))
        context = "\n\n".join(context_parts)

        self.db.add_log(
            "INFO",
            "llm_request_started",
            f"{agent['name']} is calling Ollama model {self.model.ollama_model}",
            conversation_id,
            {"agent_id": agent_id, "timeout_seconds": self.model.timeout_seconds, "num_predict": self.model.num_predict},
        )
        try:
            answer = await self.model.generate(
                system_prompt=agent["system_prompt"],
                user_prompt=user_input,
                context=context,
                agent_name=agent["name"],
                agent_role=agent.get("role", "Agent"),
            )
        except LLMRuntimeError as exc:
            self.db.add_log(
                "ERROR",
                "llm_request_failed",
                f"{agent['name']} LLM call failed: {exc}",
                conversation_id,
                {"agent_id": agent_id, "model": self.model.ollama_model},
            )
            raise

        max_words = (agent.get("guardrails") or {}).get("max_response_words", 180)
        if max_words and len(answer.split()) > max_words:
            answer = " ".join(answer.split()[:max_words]) + " ..."

        if agent.get("memory_enabled"):
            self.db.upsert_memory(agent_id, "last_user_input", user_input[:500])
            self.db.upsert_memory(agent_id, "last_answer", answer[:500])

        tokens = estimate_tokens(user_input + " " + context + " " + answer)
        self.db.add_message(
            conversation_id,
            "agent",
            str(agent_id),
            channel,
            answer,
            {"tool_trace": tool_trace, "agent_name": agent["name"], "llm_model": self.model.ollama_model, "llm_provider": "ollama"},
        )
        self.db.add_log("INFO", "agent_completed", f"{agent['name']} completed using LLM", conversation_id, {"tokens": tokens, "model": self.model.ollama_model})
        return AgentOutput(answer=answer, tool_trace=tool_trace, tokens=tokens)

    async def send_async_message(self, conversation_id: str, source_agent_id: int, target_agent_id: int,
                                 content: str, channel: str = "agent-bus") -> None:
        event = {
            "id": str(uuid.uuid4()),
            "conversation_id": conversation_id,
            "source_agent_id": source_agent_id,
            "target_agent_id": target_agent_id,
            "content": content,
            "channel": channel,
            "created_at_ms": int(time.time() * 1000),
        }
        await self.message_queue.put(event)
        self.db.add_message(conversation_id, "agent", str(source_agent_id), channel, content, {"target_agent_id": target_agent_id})
        self.db.add_log("INFO", "agent_message_queued", f"Async message queued from {source_agent_id} to {target_agent_id}", conversation_id, event)
